### PR TITLE
Fix excess decimal digits in the y-axis of the chart (fixes #390)

### LINKED ISSUE #390: Sometimes the chart shows too many decimal digits
https://openmeteo.org/stations/1458/timeseriesgroups/6/

### PR DESCRIPTION
**Pull request by eyobofficial**
Closes #390

### CODE REVIEW

File: enhydris/static/js/chart.js [hunk 1]
```diff
@@ -122,6 +122,11 @@ $(function () {
     },
     yaxis: {
       tickAmount: 2,
+      labels: {
+        formatter(val) {
+          return val.toFixed(1);
```
Comment (aptiko) [inline enhydris/static/js/chart.js:127]: Using one decimal digit here is suboptimal. You'd better use the [precision attribute](https://enhydris.readthedocs.io/en/latest/dev/database.html#enhydris.models.TimeseriesGroup.precision); something like
```
val.toFixed(precision >= 0 ? precision : 0)
```
This would still be suboptimal, but it will do for now. (A better solution would be to make sure that the ticks appear in nicer positions, e.g. for temperature they should be at 0,5, 10 degrees etc. and not in whatever random steps the chart decides—but let's leave this for the future.)

File: enhydris/static/js/chart.js [hunk 2]
```diff
@@ -190,6 +195,13 @@ $(function () {
         enabled: false,
       },
     },
+    yaxis: {
+      labels: {
+        formatter(val) {
+          return val.toFixed(1);
```
Comment (aptiko) [inline enhydris/static/js/chart.js:201]: Likewise.

File: enhydris/static/js/chart.js [hunk 3]
```diff
@@ -209,6 +221,7 @@ $(function () {
     .then((response) => response.json())
     .then((data) => {
       if (data && data[0]) {
+        console.log('Returned data: ', data);
```
Comment (aptiko) [inline enhydris/static/js/chart.js:224]: Is this a forgotten debugging statement?
